### PR TITLE
Upgrade cypress to version 10

### PR DESCRIPTION
**Pull request by AsToNlele**
Cypress is successfully upgraded to V10

I have a question whether we should have a single command for tests like:
`"test": "cypress run --component && npx nyc report"`
because we don't have any jest tests

Now it is the same way like in OCP Advisor

### CODE REVIEW

**Comment by leSamo** [comment]
> I have a question whether we should have a single command for tests like:
> "test": "cypress run --component && npx nyc report"
> because we don't have any jest tests

We could, but then PR check (ci.ext.devshift.net PR build) would fail on every PR and commit because it can't handle automated Cypress tests yet :(

**Comment by leSamo** [comment]
Hm, `npm run test:coverage` and `npm run test:ct` show error
> ENOENT: no such file or directory, scandir '/home/samueloleksak/vuln4shift-frontend/.nyc_output'

and don't display the coverage

**Comment by AsToNlele** [comment]
> Hm, `npm run test:coverage` and `npm run test:ct` show error
> 
> > ENOENT: no such file or directory, scandir '/home/samueloleksak/vuln4shift-frontend/.nyc_output'
> 
> and don't display the coverage, maybe you need to update istanbul plugin package as well, or some other package thinking

I've noticed this issue is also in OCP-Advisor, creating an empty `.nyc_output` folder fixes this, but I'll have a closer look. Cypress tests work fine otherwise.

**Comment by AsToNlele** [comment]
Sorry for the delay, I also had to fix the image matching but should be fine now.

**Comment by leSamo** [comment]
@AsToNlele, yes! Please do that.

**Comment by AsToNlele** [comment]
Images are in! :smile:

**Pull request merged**
